TOPICS = [
    ("Python'da list comprehension", 'https://docs.python.org/3/tutorial/datastructures.html#list-comprehensions'),
    ("JavaScript'da async/await qanday ishlaydi", 'https://developer.mozilla.org/en-US/docs/Learn_web_development/Extensions/Async_JS/Promises'),
    ('Git branch strategiyalari', 'https://git-scm.com/book/en/v2/Git-Branching-Branching-Workflows'),
    ('SQL indekslar nima uchun kerak', 'https://use-the-index-luke.com/'),
    ('REST API dizayn printsiplari', 'https://restfulapi.net/'),
    ("Three.js'da 3D obyektlarni animatsiya qilish", 'https://threejs.org/docs/#manual/en/introduction/Animation-system'),
    ('CSS Flexbox vs Grid qachon qaysi birini ishlatish', 'https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_grid_layout/Realizing_common_layouts_using_grids'),
    ('Docker konteynerlari nima va nega kerak', 'https://docs.docker.com/get-started/docker-overview/'),
    ("Python'da dekoratorlar", 'https://docs.python.org/3/glossary.html#term-decorator'),
    ('Web xavfsizligi: XSS va CSRF nima', 'https://owasp.org/www-community/attacks/xss/'),
    ("TypeScript nega JavaScript'dan yaxshi", 'https://www.typescriptlang.org/docs/handbook/intro.html'),
    ('Big O notation asoslari', 'https://en.wikipedia.org/wiki/Big_O_notation'),
    ("React'da useEffect qanday ishlaydi", 'https://react.dev/reference/react/useEffect'),
    ("Ma'lumotlar bazasida normalizatsiya", 'https://en.wikipedia.org/wiki/Database_normalization'),
    ('WebSocket va real-time aplikatsiyalar', 'https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API'),
    ("<Sun'iy intelektlar haqidaki yangiliklar>", None),
    ("Sun'iy intelektlar haqidaki yangiliklar", None),
]
